#' Ernie 4,0 API demo
#'
#' @param text Your question
#' @param API_KEY Obtained from bce.baidu.com
#' @param SECRET_KEY Obtained from bce.baidu.com
#'
#' @return Qianfan LLM responce
#' @export
ask_qf = function(text, API_KEY, SECRET_KEY){
  url = "https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/completions_pro?access_token="
  url = paste(url, get_access_token(API_KEY, SECRET_KEY), sep = '')
  payload = paste('{"messages": [{"role": "user", "content": "吃饭了么"},
                  {"role": "assistant", "content": "吃了五块红烧肉"},
                  {"role": "user", "content": "', text, '"}],
                   "functions":[{
            "name": "eval",
            "description": "计算器，计算以字符数书写的算式的计算结果",
            "parameters": {
                "type": "object",
                "properties": {  "numbers": {    "type": "string",  "description": "能用python中的eval函数计算的字符串算式",
                        "items": {
                            "type": "number"
                        }  }
                }
            }
        }]}    ', sep='')
  headers = c('Content-Type' = 'application/json')
  response = POST(url, headers=headers, body=payload)
  return(response)
}


#' Get token to connect LLM model
#'
#' @param API_KEY Obtained from bce.baidu.com 
#' @param SECRET_KEY Obtained from bce.baidu.com 
#'
#' @return One series generated by baidu.com
#' @export
get_access_token = function(API_KEY,SECRET_KEY){
  url = "https://aip.baidubce.com/oauth/2.0/token"
  params = list(grant_type = "client_credentials", client_id = API_KEY, client_secret = SECRET_KEY)
  temp = POST(url, body=params)
  return(content(temp)$access_token)
}